version: "3.8"

services:
  app:
    build: .
    container_name: raintree-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - raintree-network

  webserver:
    image: nginx:alpine
    container_name: raintree-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - raintree-network

  db:
    image: mysql:8.0
    container_name: raintree-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: rooter
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - raintree-network

volumes:
  db_data:

networks:
  raintree-network:
    driver: bridge
